# =========================================================
# SignAI - User Performance PDF Report
# =========================================================

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from database.database import SessionLocal
from database.models import User, PracticeHistory

from collections import defaultdict
from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether
)

router = APIRouter(
    prefix="/practice",
    tags=["Practice Report"]
)


# =========================================================
# PDF STYLES
# =========================================================

PRIMARY = colors.HexColor("#254E58")
SECONDARY = colors.HexColor("#5F8F94")
LIGHT = colors.HexColor("#EAF3F4")
SUCCESS = colors.HexColor("#10A37F")
WARNING = colors.HexColor("#F59E0B")
DANGER = colors.HexColor("#EF4444")
TEXT = colors.HexColor("#263238")
MUTED = colors.HexColor("#6B7280")


styles = getSampleStyleSheet()


title_style = ParagraphStyle(
    "ReportTitle",
    parent=styles["Title"],
    fontName="Helvetica-Bold",
    fontSize=24,
    leading=28,
    textColor=PRIMARY,
    alignment=TA_CENTER,
    spaceAfter=8
)


subtitle_style = ParagraphStyle(
    "ReportSubtitle",
    parent=styles["Normal"],
    fontName="Helvetica",
    fontSize=10,
    textColor=MUTED,
    alignment=TA_CENTER,
    spaceAfter=20
)


section_style = ParagraphStyle(
    "SectionTitle",
    parent=styles["Heading2"],
    fontName="Helvetica-Bold",
    fontSize=15,
    leading=18,
    textColor=PRIMARY,
    spaceBefore=12,
    spaceAfter=10
)


normal_style = ParagraphStyle(
    "NormalReport",
    parent=styles["Normal"],
    fontName="Helvetica",
    fontSize=9.5,
    leading=14,
    textColor=TEXT
)


small_style = ParagraphStyle(
    "SmallReport",
    parent=styles["Normal"],
    fontName="Helvetica",
    fontSize=8,
    leading=11,
    textColor=MUTED
)


# =========================================================
# PDF HEADER / FOOTER
# =========================================================

def draw_header_footer(canvas, doc):

    canvas.saveState()

    width, height = A4

    # Header line
    canvas.setStrokeColor(PRIMARY)
    canvas.setLineWidth(1)

    canvas.line(
        18 * mm,
        height - 15 * mm,
        width - 18 * mm,
        height - 15 * mm
    )

    canvas.setFont(
        "Helvetica-Bold",
        8
    )

    canvas.setFillColor(PRIMARY)

    canvas.drawString(
        18 * mm,
        height - 11 * mm,
        "SignAI"
    )

    canvas.setFont(
        "Helvetica",
        8
    )

    canvas.setFillColor(MUTED)

    canvas.drawRightString(
        width - 18 * mm,
        height - 11 * mm,
        "AI Sign Language Performance Report"
    )

    # Footer
    canvas.setStrokeColor(
        colors.HexColor("#DDDDDD")
    )

    canvas.line(
        18 * mm,
        12 * mm,
        width - 18 * mm,
        12 * mm
    )

    canvas.setFont(
        "Helvetica",
        7
    )

    canvas.setFillColor(MUTED)

    canvas.drawString(
        18 * mm,
        7 * mm,
        "Generated by SignAI"
    )

    canvas.drawRightString(
        width - 18 * mm,
        7 * mm,
        f"Page {doc.page}"
    )

    canvas.restoreState()


# =========================================================
# FORMAT HELPERS
# =========================================================

def safe(value, default="N/A"):

    if value is None:
        return default

    return str(value)


def percentage(correct, attempts):

    if attempts == 0:
        return 0

    return round(
        (correct / attempts) * 100,
        1
    )


# =========================================================
# REPORT ROUTE
# =========================================================

@router.get("/report/pdf/{user_id}")
async def download_report(user_id: int):

    db = SessionLocal()

    try:

        # =================================================
        # FIND USER
        # =================================================

        user = (
            db.query(User)
            .filter(User.id == user_id)
            .first()
        )

        if not user:

            raise HTTPException(
                status_code=404,
                detail="User not found"
            )


        # =================================================
        # GET PRACTICE HISTORY
        # =================================================

        records = (
            db.query(PracticeHistory)
            .filter(
                PracticeHistory.user_id == user_id
            )
            .order_by(
                PracticeHistory.created_at.asc()
            )
            .all()
        )


        # =================================================
        # BASIC STATISTICS
        # =================================================

        total_attempts = len(records)

        total_correct = sum(
            1
            for record in records
            if record.is_correct
        )

        total_incorrect = (
            total_attempts -
            total_correct
        )

        overall_accuracy = percentage(
            total_correct,
            total_attempts
        )


        total_xp = sum(
            record.xp_earned or 0
            for record in records
        )


        # =================================================
        # SIGN STATISTICS
        # =================================================

        sign_stats = defaultdict(
            lambda: {
                "attempts": 0,
                "correct": 0
            }
        )


        for record in records:

            sign = (
                record.target_word or
                "Unknown"
            )

            sign_stats[sign]["attempts"] += 1

            if record.is_correct:
                sign_stats[sign]["correct"] += 1


        sign_results = []


        for sign, stats in sign_stats.items():

            accuracy = percentage(
                stats["correct"],
                stats["attempts"]
            )

            sign_results.append({
                "sign": sign,
                "attempts": stats["attempts"],
                "correct": stats["correct"],
                "accuracy": accuracy
            })


        # Best signs
        best_signs = sorted(
            sign_results,
            key=lambda x: x["accuracy"],
            reverse=True
        )[:5]


        # Weak signs
        weak_signs = sorted(
            sign_results,
            key=lambda x: x["accuracy"]
        )[:5]


        # =================================================
        # DIFFICULTY STATISTICS
        # =================================================

        difficulty_stats = defaultdict(
            lambda: {
                "attempts": 0,
                "correct": 0
            }
        )


        for record in records:

            difficulty = (
                record.difficulty or
                "unknown"
            )

            difficulty_stats[
                difficulty
            ]["attempts"] += 1

            if record.is_correct:

                difficulty_stats[
                    difficulty
                ]["correct"] += 1


        # =================================================
        # STRENGTH ANALYSIS
        # =================================================

        strengths = []


        if overall_accuracy >= 85:

            strengths.append(
                "Excellent overall prediction accuracy."
            )

        elif overall_accuracy >= 70:

            strengths.append(
                "Good overall sign recognition ability."
            )

        elif overall_accuracy >= 50:

            strengths.append(
                "You are building a foundation in sign recognition."
            )

        else:

            strengths.append(
                "You have started building your sign language recognition skills."
            )


        if best_signs:

            strongest = best_signs[0]

            strengths.append(
                f"Strong performance on sign "
                f"'{strongest['sign']}' "
                f"with {strongest['accuracy']:.0f}% accuracy."
            )


        if total_correct > 0:

            strengths.append(
                f"You successfully recognized "
                f"{total_correct} sign attempts."
            )


        if user.streak and user.streak > 0:

            strengths.append(
                f"You currently have a "
                f"{user.streak}-day practice streak."
            )


        # =================================================
        # IMPROVEMENT AREAS
        # =================================================

        improvements = []


        if weak_signs:

            weakest = weak_signs[0]

            improvements.append(
                f"Practice sign '{weakest['sign']}' "
                f"more frequently "
                f"({weakest['accuracy']:.0f}% accuracy)."
            )


        if overall_accuracy < 70:

            improvements.append(
                "Focus on maintaining a consistent hand position "
                "before increasing practice difficulty."
            )


        if overall_accuracy < 50:

            improvements.append(
                "Practice slowly and make sure the complete hand "
                "is visible inside the camera frame."
            )


        if not improvements:

            improvements.append(
                "Continue practicing regularly to maintain your performance."
            )


        # =================================================
        # AI RECOMMENDATIONS
        # =================================================

        recommendations = []


        if overall_accuracy >= 85:

            recommendations.append(
                "You are performing strongly. Consider moving to "
                "a higher difficulty level."
            )

        elif overall_accuracy >= 70:

            recommendations.append(
                "Continue practicing at your current level and "
                "focus on consistency."
            )

        else:

            recommendations.append(
                "Spend more time practicing Easy-level signs "
                "before moving to harder signs."
            )


        if weak_signs:

            weak_names = ", ".join(
                str(x["sign"])
                for x in weak_signs[:3]
            )

            recommendations.append(
                f"Give additional practice time to: {weak_names}."
            )


        recommendations.append(
            "Keep your hand clearly visible and centered in the camera frame."
        )


        recommendations.append(
            "Practice consistently rather than completing many attempts "
            "in a single session."
        )


        # =================================================
        # CREATE PDF
        # =================================================

        buffer = BytesIO()


        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=18 * mm,
            leftMargin=18 * mm,
            topMargin=22 * mm,
            bottomMargin=18 * mm
        )


        story = []


        # =================================================
        # TITLE
        # =================================================

        story.append(
            Spacer(1, 10 * mm)
        )


        story.append(
            Paragraph(
                "SignAI",
                title_style
            )
        )


        story.append(
            Paragraph(
                "AI Sign Language Performance Report",
                subtitle_style
            )
        )


        # =================================================
        # USER INFORMATION
        # =================================================

        story.append(
            Paragraph(
                "USER INFORMATION",
                section_style
            )
        )


        user_data = [

            [
                Paragraph(
                    "<b>Name</b>",
                    normal_style
                ),
                Paragraph(
                    safe(user.name),
                    normal_style
                )
            ],

            [
                Paragraph(
                    "<b>Email</b>",
                    normal_style
                ),
                Paragraph(
                    safe(user.email),
                    normal_style
                )
            ],

            [
                Paragraph(
                    "<b>Current Level</b>",
                    normal_style
                ),
                Paragraph(
                    safe(user.level, "Beginner"),
                    normal_style
                )
            ],

            [
                Paragraph(
                    "<b>Report Date</b>",
                    normal_style
                ),
                Paragraph(
                    datetime.now().strftime(
                        "%d %B %Y"
                    ),
                    normal_style
                )
            ]

        ]


        user_table = Table(
            user_data,
            colWidths=[
                45 * mm,
                125 * mm
            ]
        )


        user_table.setStyle(
            TableStyle([

                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    LIGHT
                ),

                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.HexColor("#D5E3E5")
                ),

                (
                    "INNERGRID",
                    (0, 0),
                    (-1, -1),
                    0.3,
                    colors.HexColor("#E5E7EB")
                ),

                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE"
                ),

                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    8
                ),

                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    8
                ),

                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    7
                ),

                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    7
                )

            ])
        )


        story.append(user_table)


        # =================================================
        # OVERALL PERFORMANCE
        # =================================================

        story.append(
            Paragraph(
                "OVERALL PERFORMANCE",
                section_style
            )
        )


        performance_data = [

            [
                "Total Attempts",
                str(total_attempts),
                "Correct",
                str(total_correct)
            ],

            [
                "Incorrect",
                str(total_incorrect),
                "Accuracy",
                f"{overall_accuracy}%"
            ],

            [
                "XP Earned",
                str(total_xp),
                "Current Level",
                safe(user.level, "Beginner")
            ],

            [
                "Practice Streak",
                f"{user.streak or 0} days",
                "Total Sessions",
                str(
                    len(
                        set(
                            r.created_at.date()
                            for r in records
                            if r.created_at
                        )
                    )
                )
            ]

        ]


        performance_table = Table(
            performance_data,
            colWidths=[
                42 * mm,
                40 * mm,
                42 * mm,
                46 * mm
            ]
        )


        performance_table.setStyle(
            TableStyle([

                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, -1),
                    colors.white
                ),

                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    LIGHT
                ),

                (
                    "BACKGROUND",
                    (2, 0),
                    (2, -1),
                    LIGHT
                ),

                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.HexColor("#D5E3E5")
                ),

                (
                    "INNERGRID",
                    (0, 0),
                    (-1, -1),
                    0.3,
                    colors.HexColor("#E5E7EB")
                ),

                (
                    "FONTNAME",
                    (0, 0),
                    (-1, -1),
                    "Helvetica"
                ),

                (
                    "FONTNAME",
                    (0, 0),
                    (0, -1),
                    "Helvetica-Bold"
                ),

                (
                    "FONTNAME",
                    (2, 0),
                    (2, -1),
                    "Helvetica-Bold"
                ),

                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, -1),
                    TEXT
                ),

                (
                    "ALIGN",
                    (1, 0),
                    (1, -1),
                    "CENTER"
                ),

                (
                    "ALIGN",
                    (3, 0),
                    (3, -1),
                    "CENTER"
                ),

                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE"
                ),

                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    8
                ),

                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    8
                )

            ])
        )


        story.append(performance_table)


        # =================================================
        # STRENGTHS
        # =================================================

        story.append(
            Paragraph(
                "YOUR STRENGTHS",
                section_style
            )
        )


        for strength in strengths:

            story.append(
                Paragraph(
                    f"✓ {strength}",
                    normal_style
                )
            )

            story.append(
                Spacer(1, 3)
            )


        # =================================================
        # AREAS TO IMPROVE
        # =================================================

        story.append(
            Paragraph(
                "AREAS TO IMPROVE",
                section_style
            )
        )


        for improvement in improvements:

            story.append(
                Paragraph(
                    f"• {improvement}",
                    normal_style
                )
            )

            story.append(
                Spacer(1, 3)
            )


        # =================================================
        # AI RECOMMENDATIONS
        # =================================================

        story.append(
            Paragraph(
                "AI RECOMMENDATIONS",
                section_style
            )
        )


        for index, recommendation in enumerate(
            recommendations,
            1
        ):

            story.append(
                Paragraph(
                    f"{index}. {recommendation}",
                    normal_style
                )
            )

            story.append(
                Spacer(1, 3)
            )


        # =================================================
        # SIGN PERFORMANCE
        # =================================================

        story.append(
            PageBreak()
        )


        story.append(
            Paragraph(
                "SIGN-BY-SIGN PERFORMANCE",
                section_style
            )
        )


        if sign_results:

            sign_data = [
                [
                    "Sign",
                    "Attempts",
                    "Correct",
                    "Accuracy"
                ]
            ]


            for result in sorted(
                sign_results,
                key=lambda x: x["accuracy"],
                reverse=True
            ):

                sign_data.append([
                    result["sign"],
                    str(result["attempts"]),
                    str(result["correct"]),
                    f"{result['accuracy']:.1f}%"
                ])


            sign_table = Table(
                sign_data,
                colWidths=[
                    45 * mm,
                    40 * mm,
                    40 * mm,
                    45 * mm
                ],
                repeatRows=1
            )


            sign_table.setStyle(
                TableStyle([

                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, 0),
                        PRIMARY
                    ),

                    (
                        "TEXTCOLOR",
                        (0, 0),
                        (-1, 0),
                        colors.white
                    ),

                    (
                        "FONTNAME",
                        (0, 0),
                        (-1, 0),
                        "Helvetica-Bold"
                    ),

                    (
                        "ALIGN",
                        (1, 1),
                        (-1, -1),
                        "CENTER"
                    ),

                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.4,
                        colors.HexColor("#D1D5DB")
                    ),

                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [
                            colors.white,
                            LIGHT
                        ]
                    ),

                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, -1),
                        7
                    ),

                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, -1),
                        7
                    )

                ])
            )


            story.append(sign_table)

        else:

            story.append(
                Paragraph(
                    "No practice records are available yet.",
                    normal_style
                )
            )


        # =================================================
        # DIFFICULTY PERFORMANCE
        # =================================================

        story.append(
            Paragraph(
                "DIFFICULTY PERFORMANCE",
                section_style
            )
        )


        if difficulty_stats:

            difficulty_data = [
                [
                    "Difficulty",
                    "Attempts",
                    "Correct",
                    "Accuracy"
                ]
            ]


            for level in [
                "easy",
                "medium",
                "hard",
                "unknown"
            ]:

                if level not in difficulty_stats:
                    continue

                stats = difficulty_stats[level]

                difficulty_data.append([
                    level.title(),
                    str(stats["attempts"]),
                    str(stats["correct"]),
                    f"{percentage(stats['correct'], stats['attempts']):.1f}%"
                ])


            difficulty_table = Table(
                difficulty_data,
                colWidths=[
                    45 * mm,
                    40 * mm,
                    40 * mm,
                    45 * mm
                ],
                repeatRows=1
            )


            difficulty_table.setStyle(
                TableStyle([

                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, 0),
                        SECONDARY
                    ),

                    (
                        "TEXTCOLOR",
                        (0, 0),
                        (-1, 0),
                        colors.white
                    ),

                    (
                        "FONTNAME",
                        (0, 0),
                        (-1, 0),
                        "Helvetica-Bold"
                    ),

                    (
                        "ALIGN",
                        (1, 1),
                        (-1, -1),
                        "CENTER"
                    ),

                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.4,
                        colors.HexColor("#D1D5DB")
                    ),

                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [
                            colors.white,
                            LIGHT
                        ]
                    ),

                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, -1),
                        7
                    ),

                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, -1),
                        7
                    )

                ])
            )


            story.append(
                difficulty_table
            )


        # =================================================
        # RECENT HISTORY
        # =================================================

        story.append(
            PageBreak()
        )


        story.append(
            Paragraph(
                "RECENT PRACTICE HISTORY",
                section_style
            )
        )


        recent_records = list(
            reversed(records[-25:])
        )


        if recent_records:

            history_data = [
                [
                    "Date",
                    "Target",
                    "Predicted",
                    "Difficulty",
                    "Result"
                ]
            ]


            for record in recent_records:

                date_text = ""

                if record.created_at:

                    date_text = (
                        record.created_at.strftime(
                            "%d/%m/%Y"
                        )
                    )


                result = (
                    "Correct"
                    if record.is_correct
                    else "Incorrect"
                )


                history_data.append([
                    date_text,
                    safe(record.target_word),
                    safe(record.predicted_word),
                    safe(record.difficulty),
                    result
                ])


            history_table = Table(
                history_data,
                colWidths=[
                    27 * mm,
                    34 * mm,
                    34 * mm,
                    32 * mm,
                    33 * mm
                ],
                repeatRows=1
            )


            history_table.setStyle(
                TableStyle([

                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, 0),
                        PRIMARY
                    ),

                    (
                        "TEXTCOLOR",
                        (0, 0),
                        (-1, 0),
                        colors.white
                    ),

                    (
                        "FONTNAME",
                        (0, 0),
                        (-1, 0),
                        "Helvetica-Bold"
                    ),

                    (
                        "FONTSIZE",
                        (0, 0),
                        (-1, -1),
                        7.5
                    ),

                    (
                        "ALIGN",
                        (3, 1),
                        (-1, -1),
                        "CENTER"
                    ),

                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.3,
                        colors.HexColor("#D1D5DB")
                    ),

                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [
                            colors.white,
                            LIGHT
                        ]
                    ),

                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, -1),
                        5
                    ),

                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, -1),
                        5
                    )

                ])
            )


            story.append(
                history_table
            )

        else:

            story.append(
                Paragraph(
                    "No practice history available.",
                    normal_style
                )
            )


        # =================================================
        # FINAL AI SUMMARY
        # =================================================

        story.append(
            Spacer(1, 10 * mm)
        )


        story.append(
            Paragraph(
                "AI COACH SUMMARY",
                section_style
            )
        )


        if overall_accuracy >= 85:

            summary = (
                "Your performance is excellent. "
                "You demonstrate strong sign recognition "
                "and are ready to challenge yourself with "
                "more difficult signs."
            )

        elif overall_accuracy >= 70:

            summary = (
                "Your performance shows good progress. "
                "Continue practicing consistently and focus "
                "on improving the signs with lower accuracy."
            )

        elif overall_accuracy >= 50:

            summary = (
                "You are making progress, but consistency "
                "can still be improved. Focus on your weaker "
                "signs and practice them repeatedly."
            )

        else:

            summary = (
                "Your current performance indicates that "
                "more foundational practice is recommended. "
                "Focus on clear hand positioning and slow, "
                "controlled signing."
            )


        story.append(
            Paragraph(
                summary,
                normal_style
            )
        )


        story.append(
            Spacer(1, 10 * mm)
        )


        story.append(
            Paragraph(
                "Keep practicing — every attempt helps improve your AI sign recognition skills.",
                ParagraphStyle(
                    "FinalMessage",
                    parent=normal_style,
                    alignment=TA_CENTER,
                    fontName="Helvetica-Bold",
                    textColor=PRIMARY,
                    fontSize=10
                )
            )
        )


        # =================================================
        # BUILD PDF
        # =================================================

        doc.build(
            story,
            onFirstPage=draw_header_footer,
            onLaterPages=draw_header_footer
        )


        buffer.seek(0)


        filename = (
            f"SignAI_{user.name.replace(' ', '_')}_"
            f"Performance_Report.pdf"
        )


        return StreamingResponse(
            buffer,
            media_type="application/pdf",
            headers={
                "Content-Disposition":
                    f'attachment; filename="{filename}"'
            }
        )


    finally:

        db.close()